Add Webex
laravel-notification-channels/channels pull request #137
Opened 2022-02-16 07:14 UTC by askmrsinh

This adds the Webex ([https://web.webex.com](https://web.webex.com)) channel.

References:
 - https://developer.webex.com/docs/api/v1/messages/create-a-message
 - https://developer.webex.com/docs/basics#formatting-messages
 - https://developer.webex.com/docs/api/basics#message-attachments

2022-02-16 07:14 UTC, askmrsinh commented
@atymic

2022-03-23 21:26 UTC, askmrsinh commented
Can I please get a code review? @freekmurze @mpociot

2022-04-28 18:27 UTC, askmrsinh commented
@atymic 

Is this project no longer under maintenance?
I am asking since I wold like to add another channel but I don't see anything getting merged recently.

2024-02-07 19:59 UTC, askmrsinh commented
@mpociot @freekmurze - I wanted to check if anyone of you could please help me with a review and/or with setting up of a Webex channel repo?

2024-02-10 12:16 UTC, atymic requested changes
Looks good! minor changes requested. 
Will see if i can remember how to release a new channel.

2024-02-10 12:16 UTC, atymic commented on .github/workflows/coverage.yml
> +          php-version: 7.4
8.2 please

2024-02-10 12:16 UTC, atymic commented on .github/workflows/tests.yml
> +        php: [7.2, 7.3, 7.4, 8.0]
update these to 8.1 +

2024-02-10 12:16 UTC, atymic commented on .scrutinizer.yml
> +filter:
can drop this

2024-02-10 12:16 UTC, atymic commented on composer.json
> +        "illuminate/notifications": "~5.5 || ~6.0 || ~7.0 || ~8.0 || ~9.0",
only supported laravel vers needed

2024-02-10 12:16 UTC, atymic commented on composer.json
> +        "php": ">=7.2",
only supported php vers

2024-02-10 12:16 UTC, atymic commented on composer.json
> +        "phpunit/phpunit": "^8.0|^9.0"
latest phpunit please

2024-02-25 07:56 UTC, askmrsinh commented on .github/workflows/coverage.yml
> +          php-version: 7.4
Update to >=PHP 8.1 + Laravel 10

2024-02-25 07:56 UTC, askmrsinh commented on .scrutinizer.yml
> +filter:
Done!

2024-02-25 07:56 UTC, askmrsinh commented on composer.json
> +        "illuminate/notifications": "~5.5 || ~6.0 || ~7.0 || ~8.0 || ~9.0",
Update to Laravel 10

2024-02-25 07:56 UTC, askmrsinh commented on composer.json
> +        "php": ">=7.2",
Update to >=PHP 8.1

2024-02-25 07:59 UTC, askmrsinh commented on composer.json
> +        "phpunit/phpunit": "^8.0|^9.0"
Using newer PHPUnit 10, compatible with PHP 8.1

2024-02-25 08:27 UTC, askmrsinh commented on .github/workflows/tests.yml
> +        php: [7.2, 7.3, 7.4, 8.0]
Done!

2024-02-25 11:57 UTC, atymic commented
Repo created, please push code there:
https://github.com/laravel-notification-channels/Webex

Then i will release on packagist

2024-02-25 11:58 UTC, atymic approved these changes

2024-02-25 22:59 UTC, askmrsinh commented
@atymic  
I am unable to fork the repo (screenshot below), or push to it.
Also, should it be named `webex` (all lowercase) which is more in line with other channel repos?

This is what I am seeing:
![image](https://github.com/laravel-notification-channels/channels/assets/6129517/4eb9b9e9-e50d-43fe-9aa0-582e2f5a3506)

2024-02-25 23:46 UTC, askmrsinh commented
Sorry, I missed the Github invite to the repo earlier. I have pushed to the new repository.
I strongly feel it should be renamed to `laravel-notification-channels/webex`; I don't have access to do that myself.

Currently trying to get Scrutinizer setup on the new repo:
![image](https://github.com/laravel-notification-channels/channels/assets/6129517/a1a7e8a6-c78a-492a-941c-f268ebc5c318)

2024-05-20 23:46 UTC, askmrsinh commented
Moved to GitHub Actions. Closing.

2024-05-20 23:46 UTC, closed without merging