Adding Pushmix Channel
laravel-notification-channels/channels pull request #47
Opened 2019-01-22 21:29 UTC by alexpechkarev

2019-09-12 02:00 UTC, atymic commented
Hi!

Are you still open to creating and maintaining this channel?

If so, could you update it to support laravel 5.5-6.0 please?

Thanks!

2019-12-23 21:17 UTC, atymic commented
Hey @alexpechkarev 

Are you still planning on updating this channel?

2019-12-24 11:28 UTC, alexpechkarev commented
Hi @atymic

Yes, still interesting in updating the channel.

2020-01-18 00:24 UTC, atymic commented
@alexpechkarev have you had a chance to look at the channel?

2020-01-18 08:02 UTC, alexpechkarev commented
yes, the changes for Laravel 6 support have been applied.

2020-01-18 23:42 UTC, atymic commented
Oh, my bad. Will review now :)

2020-01-18 23:53 UTC, atymic requested changes

2020-01-18 23:53 UTC, atymic commented on README.md
> +# Pushmix notifications channel for Laravel 5.3+
```suggestion
# Pushmix notifications channel for Laravel 5.5+ & 6.x
```

2020-01-18 23:53 UTC, atymic commented on README.md
> +This package makes it easy to send [Pushmix notifications](https://www.pushmix.co.uk/docs/laravel-notification-channel) with Laravel 5.3+.
```suggestion
This package makes it easy to send [Pushmix notifications](https://www.pushmix.co.uk/docs/laravel-notification-channel) with Laravel 5.5+ & 6.x.
```

2020-01-18 23:53 UTC, atymic commented on README.md
> +If you're installing the package in Laravel 5.4 or lower, you must import the service provider:
remove this, since < 5.4 is not supported

2020-01-18 23:53 UTC, atymic commented on build/coverage.txt
> +Code Coverage Report:
this dir should be gitignored

2020-01-18 23:53 UTC, atymic commented on composer.json
> +    "name": "alexpechkarev/new-channels",
correct this please

2020-01-18 23:53 UTC, atymic commented on composer.json
> +        "illuminate/notifications": "6.*",
```suggestion
        "illuminate/notifications": "~5.5 | ~6.0",
```

2020-01-18 23:53 UTC, atymic commented on composer.json
> +        "illuminate/support": "6.*"
```suggestion
        "illuminate/support": "~5.5 | ~6.0",
```

2020-01-18 23:53 UTC, atymic commented on composer.json
> +      "orchestra/testbench": "^3.5",
```suggestion
      "orchestra/testbench": "~3.5 || ~4.0",
```

2020-01-18 23:53 UTC, atymic commented on composer.json
> +      "phpunit/phpunit": "^6.4"
```suggestion
      "phpunit/phpunit": "^8.0"
```

2020-01-18 23:53 UTC, atymic commented on composer.lock
> +    "_readme": [
don't commit this for packages

2020-01-18 23:53 UTC, atymic commented on phpunit.xml
> +        <log type="coverage-html" target="build/coverage" charset="UTF-8" yui="true" highlight="true"/>
```suggestion
        <log type="coverage-html" target="build/coverage"/>
```

2020-01-18 23:53 UTC, atymic commented on phpunit.xml
> +        <testsuite name="Spatie Test Suite">
Copy/paste?

2020-01-18 23:53 UTC, atymic commented on src/PushmixChannel.php
> +        $this->pusmixClient = $pusmixClient;
`pusmixClient` should be `pushmixClient`

2020-01-18 23:53 UTC, atymic commented on src/PushmixChannel.php
> +        if (! $to = $notifiable->routeNotificationFor('Pushmix')) {
```suggestion
        if (! $to = $notifiable->routeNotificationFor('Pushmix')) {
```

lowercase for routing

2020-01-18 23:53 UTC, atymic commented on src/PushmixChannel.php
> +    /***/
```suggestion
```

2020-01-18 23:53 UTC, atymic commented on src/PushmixClient.php
> +    protected $client;
docblocks please

2020-01-18 23:53 UTC, atymic commented on src/PushmixClient.php
> +    protected $api_url = 'https://www.pushmix.co.uk/api/notify';
this can be a const

2020-01-18 23:53 UTC, atymic commented on src/PushmixClient.php
> +        $this->additionalParams = [
formatting is wonky here

2020-01-18 23:53 UTC, atymic commented on src/PushmixClient.php
> +    /***/
Can you remove all these?

2020-01-18 23:53 UTC, atymic commented on src/PushmixClient.php
> +        $this->headers['body'] = json_encode($parameters);
`$this->headers` should be called something like `$this->requestOptions`, as it doesnt contain headers

2020-01-18 23:53 UTC, atymic commented on src/PushmixServiceProvider.php
> +    /***/
as with other files, remove this

2020-01-18 23:54 UTC, atymic commented
Have added some review comments, re-request a review once you've looked over/fixed the issues :)

2021-05-18 01:12 UTC, closed without merging

2021-05-18 01:12 UTC, atymic commented
Closing due to inactivity, ping me once changes are made.