add TotalVoice Channels request
laravel-notification-channels/channels pull request #50
Opened 2019-02-14 20:58 UTC by hafael

This package makes it easy to send [TotalVoice Notifications](https://api.totalvoice.com.br/doc) with Laravel 5.3+.

[TotalVoice](https://www.totalvoice.com.br) is an api based platform focused in provide communications by voice and text in brazilian territory (pay-as-you-go Reais R$).

This package allows you to send Laravel Notifications such as audio call, text-to-speech call and text sms.

2019-09-10 11:32 UTC, atymic commented
Hi!

Are you still open to creating and maintaining this channel?

If so, could you update it to support laravel 5.5-6.0 please?

Thanks!

2019-09-27 23:56 UTC, atymic commented
cc @hafael

2019-09-28 00:51 UTC, hafael commented
@atymic Yes! I will update in the next few hours. Thanks!

2019-09-28 21:44 UTC, hafael commented
@atymic done!

2019-10-21 00:16 UTC, atymic commented on .styleci.yml
> +preset: laravel
newline please

2019-10-21 00:24 UTC, atymic requested changes
Hey :) 

Thanks for the PR. Please see comments.
Overall, looks good and I'll create a repo once the comments are addressed!

2019-10-21 00:24 UTC, atymic commented on .travis.yml
> +  - 5.6
Only 7.2 and 7.3/nightly for travis please

2019-10-21 00:24 UTC, atymic commented on README.md
> +# TotalVoice notifications channel for Laravel 5.3+
```suggestion
# TotalVoice notifications channel for Laravel
```

2019-10-21 00:24 UTC, atymic commented on README.md
> +This package makes it easy to send [TotalVoice Notifications](https://api.totalvoice.com.br/doc) with Laravel 5.3+.
```suggestion
This package makes it easy to send [TotalVoice Notifications](https://api.totalvoice.com.br/doc) with Laravel 5.5+ & 6.x.
```

2019-10-21 00:24 UTC, atymic commented on README.md
> +Add the service provider (only required on Laravel 5.4 or lower):
Don't worry about this (since we are not supporting < 5.5)

2019-10-21 00:24 UTC, atymic commented on composer.json
> +        "illuminate/notifications": "5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*|6.0.*",
```suggestion
        "illuminate/notifications": "~5.5 || ~6.0",
```

(and below)

2019-10-21 00:24 UTC, atymic commented on composer.json
> +        "php": ">=5.6.4",
```suggestion
        "php": ">=7.2",
```

2019-10-21 00:24 UTC, atymic commented on composer.json
> +        "mockery/mockery": "^0.9.5",
```suggestion
        "mockery/mockery": "^1.0",
```

2019-10-21 00:24 UTC, atymic commented on composer.json
> +        "phpunit/phpunit": "4.*"
```suggestion
        "phpunit/phpunit": "8.*"
```

2019-10-21 00:24 UTC, atymic commented on phpunit.xml.dist
> +        <log type="coverage-html" target="build/coverage" charset="UTF-8" yui="true" highlight="true"/>
```suggestion
        <log type="coverage-html" target="build/coverage"/>
```

Otherwise tests will fail on new PHP unit versions

2019-10-21 00:24 UTC, atymic commented on phpunit.xml.dist
> +</phpunit>
Newline

2019-10-21 00:24 UTC, atymic commented on src/Exceptions/CouldNotSendNotification.php
> +            "Notification was not sent. Message object class `{$className}` is invalid. It should
Can we please use `sprintf` here rather than concatenation

2019-10-21 00:24 UTC, atymic commented on src/TotalVoice.php
> +                                                    trim($message->content),
Please place each param on a new line, with 4 space alignment.

2019-10-21 00:24 UTC, atymic commented on src/TotalVoiceAudioMessage.php
> +    public static function create($audio_url = '')
camelcase variable names please

2019-10-21 00:24 UTC, atymic commented on src/TotalVoiceChannel.php
> +            if (function_exists('event')) {
Curious as to the reason for this code?

2019-10-21 00:24 UTC, atymic commented on src/TotalVoiceConfig.php
> +     * TotalVoiceConfig constructor.
can remove this :)

2019-10-21 00:24 UTC, atymic commented on src/TotalVoiceMessage.php
> +    public static function create($content = '')
Can we add typehints here?

2019-10-21 00:24 UTC, atymic commented on src/TotalVoiceMessage.php
> +    public function provideFeedback($provide_feedback)
Camelcase and `bool` typehint please

2019-10-21 00:24 UTC, atymic commented
Only other thing is, can you please add some tests :)

2020-01-14 21:38 UTC, atymic commented
@hafael have you had a chance to review the above feedback?

2020-04-28 10:10 UTC, atymic commented
Closing this. Feel free to ping me to re-open once you address the feedback.

2020-04-28 10:10 UTC, closed without merging